(autoload 'window-coords                        "frame-fns" "" nil)
(autoload 'distance                             "frame-fns" "" nil)
(autoload 'frame-geom-value-numeric             "frame-fns" "" nil)
(autoload 'frame-geom-spec-numeric              "frame-fns" "" nil)
(autoload 'frame-geom-value-cons                "frame-fns" "" nil)
(autoload 'frame-geom-spec-cons                 "frame-fns" "" nil)
(autoload 'get-frame-name                       "frame-fns" "" nil)
(autoload 'get-a-frame                          "frame-fns" "" nil)
(autoload 'read-frame                           "frame-fns" "" nil)
(autoload 'frames-on                            "frame-fns" "" nil)
(autoload '1-window-frames-on                   "frame-fns" "" nil)
(autoload 'multi-window-frames-on               "frame-fns" "" nil)
(autoload 'flash-ding                           "frame-fns" "" nil)
(provide 'lib-frame-fns-epkg-autoloads)
